apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
type: Opaque
stringData:
  access-key: minioadmin
  secret-key: minioadmin
---
apiVersion: v1
kind: Secret
metadata:
  name: kong-db-secret
type: Opaque
stringData:
  password: kong
---
apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
type: Opaque
stringData:
  secret-key: supersecretkey123
  db-url: postgresql://postgres:password@postgres:5432/groupsapp
