apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong
  labels:
    app: kong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kong
  template:
    metadata:
      labels:
        app: kong
    spec:
      containers:
      - name: kong
        image: kong:3.4
        env:
        - name: KONG_DATABASE
          value: "postgres"
        - name: KONG_PG_HOST
          value: "kong-database"
        - name: KONG_PG_PASSWORD
          value: "kong"
        - name: KONG_PG_USER
          value: "kong"
        - name: KONG_PG_DB
          value: "kong"
        - name: KONG_PROXY_ACCESS_LOG
          value: "/dev/stdout"
        - name: KONG_ADMIN_ACCESS_LOG
          value: "/dev/stdout"
        - name: KONG_PROXY_ERROR_LOG
          value: "/dev/stderr"
        - name: KONG_ADMIN_ERROR_LOG
          value: "/dev/stderr"
        ports:
        - containerPort: 8000
          name: proxy
        - containerPort: 8443
          name: proxy-ssl
        - containerPort: 8001
          name: admin
        - containerPort: 8444
          name: admin-ssl
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: kong
spec:
  selector:
    app: kong
  ports:
  - name: proxy
    protocol: TCP
    port: 80
    targetPort: 8000
  - name: proxy-ssl
    protocol: TCP
    port: 8443
    targetPort: 8443
  - name: admin
    protocol: TCP
    port: 8001
    targetPort: 8001
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: kong-database
spec:
  selector:
    app: kong-database
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong-database
  labels:
    app: kong-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kong-database
  template:
    metadata:
      labels:
        app: kong-database
    spec:
      containers:
      - name: kong-database
        image: postgres:15
        env:
        - name: POSTGRES_USER
          value: "kong"
        - name: POSTGRES_DB
          value: "kong"
        - name: POSTGRES_PASSWORD
          value: "kong"
        volumeMounts:
        - name: kong-data
          mountPath: /var/lib/postgresql/data
        resources:
          limits:
            memory: "256Mi"
            cpu: "250m"
          requests:
            memory: "128Mi"
            cpu: "100m"
      volumes:
      - name: kong-data
        emptyDir: {}