# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\x12\x04\x61uth\"\x1d\n\x0cTokenRequest\x12\r\n\x05token\x18\x01 \x01(\t\"R\n\rTokenResponse\x12\x10\n\x08is_valid\x18\x01 \x01(\x08\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x0f\n\x07user_id\x18\x03 \x01(\x05\x12\x0f\n\x07message\x18\x04 \x01(\t2G\n\x0b\x41uthService\x12\x38\n\rValidateToken\x12\x12.auth.TokenRequest\x1a\x13.auth.TokenResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TOKENREQUEST']._serialized_start=20
  _globals['_TOKENREQUEST']._serialized_end=49
  _globals['_TOKENRESPONSE']._serialized_start=51
  _globals['_TOKENRESPONSE']._serialized_end=133
  _globals['_AUTHSERVICE']._serialized_start=135
  _globals['_AUTHSERVICE']._serialized_end=206
# @@protoc_insertion_point(module_scope)
